// Auth types
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Activities types
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_FAILURE = 'ADD_ACTIVITY_FAILURE';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_FAILURE = 'DELETE_ACTIVITY_FAILURE';
export const GET_ACTIVITIES_BEGIN = 'GET_ACTIVITIES_BEGIN';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_FAILURE = 'GET_ACTIVITIES_FAILURE';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAILURE = 'UPDATE_ACTIVITY_FAILURE';
export const RESET_ADD_ACTIVITY = 'RESET_ADD_ACTIVITY';

// Logs types
export const ADD_LOG_SUCCESS = 'ADD_LOG_SUCCESS';
export const ADD_LOG_FAILURE = 'ADD_LOG_FAILURE';
export const UPDATE_LOG_SUCCESS = 'UPDATE_LOG_SUCCESS';
export const UPDATE_LOG_FAILURE = 'UPDATE_LOG_FAILURE';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';
export const DELETE_LOG_FAILURE = 'DELETE_LOG_FAILURE';
export const GET_ACTIVITY_LOGS_BEGIN = 'GET_ACTIVITY_LOGS_BEGIN';
export const GET_ACTIVITY_LOGS_SUCCESS = 'GET_ACTIVITY_LOGS_SUCCESS';
export const GET_ACTIVITY_LOGS_FAILURE = 'GET_ACTIVITY_LOGS_FAILURE';
export const EMPTY_LOGS = 'EMPTY_LOGS';
export const RESET_GET_LOGS = 'RESET_LOGS_STATUS';
export const RESET_UPDATE_LOG = 'RESET_UPDATE_LOG';

// Form types
export const NEW_LOG_FORM = 'NEW_LOG_FORM';
export const NEW_ACTIVITY_FORM = 'NEW_ACTIVITY_FORM';
export const HIDE_FORM = 'HIDE_FORM';